# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rioni < Formula
  desc "Rioni is a free and open-source DNS proxy server."
  homepage "https://github.com/AndreySenov/rioni"
  version "1.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.4/rioni-1.2.4-darwin-x86_64.tar.gz"
      sha256 "7a42d348e1678b8278d9c3d47df53e7bfaade39488b3dca4482e3d1abf0b9b90"

      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.4/rioni-1.2.4-darwin-arm64.tar.gz"
      sha256 "52460c621f6ea42408c2b81d616f41c88778e4f8e145b1a1968d8569ba86add7"

      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.4/rioni-1.2.4-linux-x86_64.tar.gz"
      sha256 "0b5338621f6fbe473f6ea2504aa123c5ef024ef3f3fc3eaa8e09d7a0e50135bc"
      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.4/rioni-1.2.4-linux-arm64.tar.gz"
      sha256 "b81bfeb7ef29286272203379b2c01432f20e0600a668bb8ff8a3a73401e93b9f"
      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
  end

  service do
    environment_variables(
      RIONI_CONFIG_FILE: /etc/"rioni/configs/rioni.cfg.yml",
      RIONI_SERVER_HTTP_TLS_CERT_FILE: etc/"rioni/tls/rioni.crt",
      RIONI_SERVER_HTTP_TLS_KEY_FILE: etc/"rioni/tls/rioni.key",
    )
    run [opt_bin/"rioni"]
    keep_alive true
  end

  test do
    system "#{bin}/rioni", "--version"
  end
end
