# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rioni < Formula
  desc "Rioni is a free and open-source DNS proxy server."
  homepage "https://github.com/AndreySenov/rioni"
  version "1.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.5/rioni-1.2.5-darwin-x86_64.tar.gz"
      sha256 "ef8cfd6775bb0fffcf731a0f586200168c88dd0c5e290b26aef54f6509abe9cf"

      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.5/rioni-1.2.5-darwin-arm64.tar.gz"
      sha256 "769e5daa6abea79f2780eebbef1d0063542c2a53e428d2540b792dca6cd2f738"

      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.5/rioni-1.2.5-linux-x86_64.tar.gz"
      sha256 "050f3528455b1cf1b1ff5fd05901199f0f3359d726ec683e51e6832f3b29ce62"
      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreySenov/rioni/releases/download/v1.2.5/rioni-1.2.5-linux-arm64.tar.gz"
      sha256 "9eb26ffa3bfad78872aeadbd78709120512446e829fe5b51633542a3abe2139d"
      define_method(:install) do
        bin.install "rioni"
        (etc/"rioni/configs").install "configs/rioni.cfg.yml"
        doc.install "README.md"
        doc.install "NOTICE"
        doc.install "LICENSE"
        (doc/"licenses").install Dir["licenses/*"]
        (doc/"docs").install Dir["docs/*"]
      end
    end
  end

  service do
    environment_variables(
      RIONI_CONFIG_FILE: /etc/"rioni/configs/rioni.cfg.yml",
      RIONI_SERVER_HTTP_TLS_CERT_FILE: etc/"rioni/tls/rioni.crt",
      RIONI_SERVER_HTTP_TLS_KEY_FILE: etc/"rioni/tls/rioni.key",
    )
    run [opt_bin/"rioni"]
    keep_alive true
  end

  test do
    system "#{bin}/rioni", "--version"
  end
end
